name: Sync to Hugging Face

on:
  push:
    branches: [main] # Agar aapki branch ka naam 'master' hai, toh yahan 'master' likhein

  # Yeh option hume workflow ko manually run karne ki suvidha deta hai
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true # Agar project me badi files (LFS) hain toh yeh zaroori hai

      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git push -f https://alpha1787:$HF_TOKEN@huggingface.co/spaces/alpha1787/Web_demo main
